<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ClientEngagementFlow.Worker-b125b63d-adc8-41e2-97ca-a8ebbe84bd77</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.21.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientEngagementFlow.Application\ClientEngagementFlow.Application.csproj" />
    <ProjectReference Include="..\ClientEngagementFlow.Infrastructure\ClientEngagementFlow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
